### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by KyGost** [gluesql/gluesql#118]
Hi--

Indexing is a crucial trait for any big data set and is generally something that helps performance.
At the moment I can't see any form of indexing for GlueSQL and my queries seem to run through the *entire* database (which is terribly slow); has anyone been looking at indexing?

If not, perhaps I can give it a bit of a go. Could someone point me in the direction of how I might get started in figuring out how GlueSQL runs/where I'd start to look at implementing indexing?

Also, aside: is there anywhere you guys communicate? I couldn't find a discord or anything alike.

**Comment by panarch** [comment]
That's right, currently GlueSQL does not have indexing feature.

It is one of remaining big core sql functionalities which needs to be supported,
* Transaction
* Foreign Key
* Index

Index is surely on the plan to implement, and if you have interest on contribution then we can reach the goal quite faster :)
I'm so glad that you tried using GlueSQL, and I'll help you to figure out.

* https://discord.gg/X4c9sJ9k
I just opened a discord channel, here is the link.

**Comment by KyGost** [comment]
Sounds good. Thanks for the link :-)

**Comment by Redblueflame** [comment]
I can help on the indexing part.
But before even starting to do anything, I have some questions on how you want the indexes to work, to make it consistent for both developers & back-ends implementations.
The current propositions (with its pros and cons)

### Create a schema using the currently implemented functions
When creating an index, create a custom table with the indexed field as primary, and the primary key of the main table as the secondary values.

**Why is it possible ?**

At least in the JS & sled backends, the real thing behind is a key value store. So adding a custom schema with only the indexed field & the primary key for lookups in the main schema causes only two BTrees lookups, instead of a crawl of all entries.
**Pros & cons**
+ Allows for backwards compatibility with the current implementation (because of the state of the program, it's not really a pro)
- Makes it less performant, as some storage back-ends could use the different types for more performant crowls & indexing.


### Offload everything to the optional back-end implementation
Create a `Indexable` (optional trait) for the back-end that will be called when an index is created (`insert_index(...)`). The indexing of the newly added elements should be handled manually by the backend (it keeps track of the indexed fields)

**Pros & Cons**
+ Allows for the most customization for the back-end implementation
+ Could be the most performant solution
+ Allows for backwards compatibility (if indexing is not needed)
+ Future proof, if a better implementation that a BTree is found, work is only needed on the back-end, leaving the main code as agnostic as possible
- Takes up more storage (could be seen in sled)
- The back-end implementation has to manage how to check the indexed fields

A variant to it could be to add an `index_row(...)` function in the `Indexable` trait, but it means that glue has to keep track itself of the indexed fields (a custom schema could be created & maintained for this purpose, and others).

**Comment by willy610** [comment]
Did some work one meta_tables. Might be useful for index design. 

Indextype could be, I think
1. primary (implicit unique)
2. unique (and ordered as option)
3. ordered

Perhaps multicolumn index should/could be built using single column index.

What about temporary index on the fly, if no ordered indexes are available.
 Would speed up joins significant

![modell](https://user-images.githubusercontent.com/6205759/99998329-cfe72400-2dbe-11eb-831c-fa72f0b4351b.png)


Partly filled 

```
here > ./target/debug/abc_sql --olddb examples/meta_tables/db --insql examples/meta_tables/offdb/show_all.sql --printsqlstm
select * from tables

+--------------+
|  tablename   |
+--------------+
| tables       |
| tablecolumns |
| indexes      |
| indexmembers |
| fk           |
+--------------+

select * from tablecolumns

+--------------+------------+------+---------+--------+
|  tablename   | columnname | kind | default | nonull |
+--------------+------------+------+---------+--------+
| tables       | tablename  | text |         | true   |
| tablecolumns | tablename  | text |         | true   |
| tablecolumns | columnname | text |         | true   |
| tablecolumns | kind       | text |         | true   |
| tablecolumns | default    | text |         | true   |
| tablecolumns | nonull     | text |         | true   |
+--------------+------------+------+---------+--------+

select * from indexes

+--------------+-----------+-----------+
|  tablename   | indexname | indexkind |
+--------------+-----------+-----------+
| tables       | primary   | unique    |
| tablecolumns | primary   | unique    |
+--------------+-----------+-----------+

select * from indexmembers

+--------------+-----------+------------+
|  tablename   | indexname | columnname |
+--------------+-----------+------------+
| tables       | primary   | tablename  |
| tablecolumns | primary   | tablename  |
| tablecolumns | primary   | columnname |
| indexes      | primary   | columnname |
+--------------+-----------+------------+

select * from fk

+--------------+----------+
|  tablename   |  fkname  |
+--------------+----------+
| tablecolumns | to_table |
+--------------+----------+

select * from fkmembers

+--------------+----------+------------+-----------+-----------+
|  tablename   |  fkname  | fromcolumn |  totable  | tocolumn  |
+--------------+----------+------------+-----------+-----------+
| tablecolumns | to_table | tablename  | tablename | tablename |
+--------------+----------+------------+-----------+-----------+

OK InSql
here > 
```

**Comment by Redblueflame** [comment]
@willy610 The unique is pretty interesting and could be useful in our case.
But if we are using a BTree for that (allows us to reduce greatly the search time on indexed fields), the ordered part will be a little bit more difficult, and even more if we stick to the 1 file database.

If you want to tale more about it, I'll be better to do so on the discord server, available here: https://discord.gg/C6TDEgzDzY

**Comment by willy610** [comment]
@Redblueflame  I have not sufficient knowledge of capabilties of ``sled`` and/or the demands from ``gluesq``l 
on any storage provider today or in the future.

Given that I prefer this 'issue story telling' more than chat which I think is more suitable for details discussions.
At the moment!

So

The benifit of index is speed and but also a requirement for reasonable fast integrity stability.

Before suggestion solutions I think it would be useful too look into

### Use Cases

1. Runtime
How to discover the proper indexes to speed readings (select, join and where)
The value of index could bee on  ordering and uniqness but for columns with domainsize the same as number of rows
there are drawbacks. Don't add index everwhere.
(write some pseudocode in pseduo-SQL!)
How to maintain all indexes content att INSERT/UPDATE/DELETE/CASCADE
(write some pseudocode in pseduo-SQL!)

2. Administration
Will probaly requires of lot of index updates! meta_tables and custom data!!!
CREATE TABLE
ALTER TABLE
ALTER TABLE (constraint)
DROP TABLE

Could the meta-table model be translated from relationel to a key-value approach?
Still one must have a uniq key capability in user data storage.
