### ISSUE TITLE
JS/react component for viewing / editing output of https://github.com/gluesql/gluesql/blob/main/pkg/javascript/src/payload.rs ?

### ISSUE THREAD

**Issue by zeroexcuses** [gluesql/gluesql#1305]
As I learned in a previous issue, by using https://github.com/gluesql/gluesql/blob/main/pkg/javascript/src/payload.rs , we can convert a Rust Payload to very nicely formatted Json.

Question: Is there some JS / react component that allows us to :
(1) visualize this json nicely (as nested dom / table, rather than txt)
(2) display uneditable fields as readonly; display editable fields as inputs, allowing edits to be sent back (via StoreMut trait) ?

Thanks!

**Comment by panarch** [comment]
> (1) visualize this json nicely (as nested dom / table, rather than txt)

that would be really nice if we have one.
however for now as I know, there no third party component for this kind of visualization.

> (2) display uneditable fields as readonly; display editable fields as inputs, allowing edits to be sent back (via StoreMut trait) ?

Rather than handling `StoreMut` directly, it is recommended to use SQL or AST Builder interface.
`StoreMut` trait is designed for the use from the GlueSQL execution layer.
We can still directly use `StoreMut` without execution layer but that might cause unexpected problem (data conflict, etc..)

**Comment by zeroexcuses** [comment]
> Rather than handling StoreMut directly, it is recommended to use SQL or AST Builder interface. StoreMut trait is designed for the use from the GlueSQL execution layer.

I completely agree with you (and mis spoke earlier). What I meant to express was:
  * use Store vs StoreMut to infer whether a field is view-only (div) or editable (input)
  * send updates back via SQL statement (for those supported by StoreMut)
 
i.e. some type of "direct / real time" manipulation of the data

**Comment by panarch** [comment]
> use Store vs StoreMut to infer whether a field is view-only (div) or editable (input)

cause we don't have a `View` feature, so every field is editable.
supported column constraints are `DEFAULT`, `NULL | NOT NULL`, or `UNIQUE | PRIMARY KEY`. so all of them are not related to mutability.

> send updates back via SQL statement (for those supported by StoreMut)

sending updates back via SQL statement is totally fine and it is also intended use.
Oh, I got that. you mean that you need a kind of data change watcher of subscribing feature?
We consider to have that functionality by extending custom store traits (like Transaction, Index, IndexMut, ..), but currently that data change watching functionality is not implemented in execution layer level.
but if you want to use on your custom storage implementation, that can work because you can add that feature to your `StoreMut` implementation.

**Comment by zeroexcuses** [comment]
Yeah -- I made a mistake here, I misunderstood the signature of StoreMut -- the original idea I had in mind does not work.
