### ISSUE TITLE
[Feature Request] Make gluesql::Row more ergonomic

### ISSUE THREAD

**Issue by the-wondersmith** [gluesql/gluesql#255]
I'm still a little new to Rust (as evidenced by my previous issue posting), so if what I propose is either impossible, impractical, or... un-Rust-like I'll close the issue and forget all about it. That said, I was wondering if it would be possible to make the `glusql::Row` type act more like a transparent type wrapper for its underlying `Vec<Value>`member.

I can't find very solid examples in rust of what I mean by "transparent type wrapper", but in Python it would be roughly equivalent to something like:

```python
class GlueSQLRow:
    """A single row of values in a database table."""

    __values__: List[Value]
    
    def __init__(self, *values: Any) -> None:
        self.__values__ = list(values)

    def __repr__(self):
        return self.__values__.__repr__()

    def __getattribute__(self, key: str) -> Any:
        return self.__values__.__getattribute__(key)

    def __getitem__(self, item: int):
        return self.__values__.__getitem__(item)
```

If any of the following is wrong, please **please** correct me. I understand that the reason(s) behind `gluesql::Row` needing to be defined to begin with have to do with Rust's type-safety guarantees and rules about not allowing crates to implement traits on types that don't belong to said crate. When you get right down to it, `gluesql::Row` is literally just `Vec<Value>` but since you can't implement behavior on types from outside your own crate and `Vec` comes from the standard library, here we are.

I did find references to the "newtype pattern" when searching for documentation that would help me explain this or even better write a PR. The "newtype pattern" appears to be what `Row` is doing anyway though, so I may or may not have the correct understanding of that. I can't quite piece together the correct query to get Google to help me find which traits would need to implemented to mimic the same behavior as the Python class above, but if I understood correctly it *MIGHT* be something like:

```rust
use std::convert::{AsMut, AsRef, From, Into};
use std::ops::{Deref, DerefMut, Index, IndexMut};

impl Deref for Row {
    fn deref(&self) -> &Vec<Value> {
        self.0.deref()
    }
}

impl DerefMut for Row {
    fn deref_mut(&mut self) -> &mut Vec<Value> {
        self.0.deref_mut()
    }
}

impl AsMut<Vec<Value>> for Row {
    fn as_mut(&mut self) -> &mut Vec<Value> {
        self.0.as_mut()
    }
}

impl AsRef<Vec<Value>> for Row {
    fn as_ref(&self) -> &Vec<Value> {
        self.0.as_ref()
    }
}

impl From<Vec<Value>> for Row {
    fn from(values: Vec<Value>) -> Self {
        Row(values)
    }
}

impl Into<Vec<Value>> for Row {
    fn into(&self) -> Vec<Value> {
        self.0.to_owned()
    }
}
```

Granted, I'm *nearly positive* the code above isn't correct. Hopefully it's close enough for communication purposes though.

I'm aware that this may be a bit much just to be able to do `row.method()` instead of having to do `row.0.method()`, but if I was going to learn how to stop myself from fixating on silly things like that I'd have done so by now, so... here we are  ¯\\_(ツ)_/¯.

Anyway, does any of that make sense? Is it even possible in Rust? If so, could you point me in the right direction for the docs that explain it and would you accept a PR if I wrote one?

**Comment by panarch** [comment]
@the-wondersmith Good question, thanks for asking this. For me, it became also very meaning time to re-think about `Row`.

"newtype pattern" looks also good, but how about this? We might be able to think of `Row` little bit differently.
`Row` struct wrapper for `Vec<Value>` is useful in internal implementation, but it may be not for end-users.

Current `SELECT` query result data format is shape of
```rust
Select {
  labels: Vec<String>,
  rows: Vec<Row>,
}
```
but, we can simply use
```rust
Select {
  labels: Vec<String>,
  rows: Vec<Vec<Value>>,
}
```
`Value` is obviously what all users need to be aware of, but `Row` is not.

Then, if someone wants to extend `Vec<Value>`, they can use `trait` to extend like this,
* https://github.com/gluesql/gluesql/blob/main/src/data/string_ext.rs

So, rather than adding more layers to `Row`, how about changing `Payload::Select` not to use `Row`?
Then, `Row` can still work well for internal development and db users don't need to care of `Row` anymore.

**Comment by the-wondersmith** [comment]
@panarch If I'm understanding your proposition correctly, then absolutely that sounds like a perfectly viable way to get what I was after I suppose.

I am still curious though, if a more experienced Rust dev could point me in the correct direction to the relevant documentation I'd need to write something like the transparent type wrapper I described.

**Comment by panarch** [comment]
@the-wondersmith oh sorry I missed your comment.
I'll add an issue related to this. removing `Row` in `Payload::Select`.

I'm not sure about the transparent type wrapper.
However, in Rust, I don't think that kind of specific pattern is important.
In the case of your code example,

```rust
impl Deref for Row { .. }
impl DerefMut for Row { .. }
impl AsMut<Vec<Value>> for Row { .. }
impl AsRef<Vec<Value>> for Row { .. }
impl From<Vec<Value>> for Row { .. }
impl Into<Vec<Value>> for Row { .. }
```
For these above traits, they all have their own purposes.
Rather than thinking about the pattern, we can simply think by the purpose.

If `AsMut` is required, then we can add.
We can do same works for other traits, too.
