### ISSUE TITLE
support multi-threaded memory-sharing features

### ISSUE THREAD

**Issue by marvinpan8** [gluesql/gluesql#493]
Can the MemoryStorage support multi-threaded memory-sharing features? Like supporting MVCC

**Comment by panarch** [comment]
Good suggestion, thanks.
I think it would be good to make another storage rather than adding multi-threaded feature to `MemoryStorage`. `SharedMemoryStorage` may work.

Limiting the scope to single-threaded makes codes extremely simple, as we see the codes in `MemoryStorage`.
I expected the role of `MemoryStorage` as, not just production-ready single-threaded in-memory storage, but also it can be the good guide document for someone who considers to make their own custom storages.

`SharedMemoryStorage`, I don't have plan to make it by myself at least until this year, but anyone can dive into this task :)

**Comment by ever0de** [comment]
> Good suggestion, thanks. I think it would be good to make another storage rather than adding multi-threaded feature to `MemoryStorage`. `SharedMemoryStorage` may work.
> 
> Limiting the scope to single-threaded makes codes extremely simple, as we see the codes in `MemoryStorage`. I expected the role of `MemoryStorage` as, not just production-ready single-threaded in-memory storage, but also it can be the good guide document for someone who considers to make their own custom storages.
> 
> `SharedMemoryStorage`, I don't have plan to make it by myself at least until this year, but anyone can dive into this task :)

I'm going to take it as a sub task.
But since it can work for a very long time, anyone can take this issue.
