### ISSUE TITLE
"fetch failed - expired transaction has used (txid)" error after sled import

### ISSUE THREAD

**Issue by raindust** [gluesql/gluesql#533]
I want to migrate data from an existing gluesql database using sled inner function `export` and `import`, but after imported even a query operation will throw "fetch failed - expired transaction has used (txid)" error.

The following is a simple example inspired by unit test sled_transaction_gc in "sled_transaction.rs":
```rust
    let path = &format!("{}/transaction_gc", PATH_PREFIX);
    fs::remove_dir_all(path).unwrap_or(());

    let storage1 = SledStorage::new(path).unwrap();
    let mut glue1 = Glue::new(storage1);

    // add some tables and data...

    let storage = glue1.storage.unwrap();
    let exports = storage.tree.export();

    let path3 = &format!("{}/transaction_gc3", PATH_PREFIX);
    fs::remove_dir_all(path3).unwrap_or(());

    let storage3 = SledStorage::new(path).unwrap();
    storage3.tree.import(exports);
    let mut glue3 = Glue::new(storage3);

    test!(glue3 "SELECT * FROM NewGarlic", Err(Error::StorageMsg("fetch failed - expired transaction has used (txid)".to_owned())));
```

The `txid` after imported does not sync as desired. So is there anything else I should do to let pass, or there is another way to migrate database?

**Comment by panarch** [comment]
Thanks! I checked and found what causes this error.
GlueSQL's SledStorage depends on [sled::generate_id](https://docs.rs/sled/latest/sled/struct.Db.html#method.generate_id) to generate unique id for internal uses (data keys, transaction keys, etc...)
`generate_id` guarantees unique id generation. However, this looks that id counter does not migrate when `sled::export` and `sled::import`.
`sled::export` only exports data and it does not contain id counter.

I will fix this issue by providing `SledStorage::export` and `SledStorage::import` functions which exports & imports generated id counter info.

For right now... if you want to migrate in urgent, there would be two tricky ways to consider.
1. After `tree.export` & `tree.import`, then... call `tree.generate_id()` repeately until you see `fetch failed - expired transaction has used (txid)` error.
2. Simply copy the entire sled data directory rather than `sled export & import`
