### ISSUE TITLE
Simplify repetitive `#[derive(Debug, Clone, PartialEq, ...)]`macros by adding proc-macro subcrate.

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#555]
# Problem and Suggestion
![image](https://user-images.githubusercontent.com/41038636/168586029-ca5fdde6-e2c9-4ace-a0ba-32b37f086078.png)
I see repetitive use of `#derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]` across several `struct`s in `gluesql-core`. I came up with an idea to simplify this using proc macro.
```rust
// before
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SetExpr {
    Select(Box<Select>),
    Values(Values),
}

// after
#[basic_derives]
pub enum SetExpr {
    Select(Box<Select>),
    Values(Values),
}
```
For few `struct` that needs extra `Display` trait in derive macro, we can do it like this.
```rust
// before
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Display)]
pub enum Function {
    #[strum(to_string = "ABS")]
    Abs(Expr),
    ...

// after
#[basic_derives(add = ["Display"])]
pub enum Function {
    #[strum(to_string = "ABS")]
    Abs(Expr),
    ...
```
With the same method we can also add `remove` attribute in that proc macro to prune out several traits.
Let me know if this idea is good or bad.

**Comment by panarch** [comment]
Idea is really good, I also read the draft codes but there's some points we need to consider.
It would be great if we can declare what to assign in the `gluesql-core` workspace, not in the new crate `gluesql-pm`.
Currently, `gluesql-pm` exists as a separate crate but it is strongly dependent to `gluesql-core`.
Then, though `basic_derives` approach can reduce some amount of codes but it can also make the codes less readable.

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
```
Though this derive code looks verbose, users can directly understand what the role it does.
However, after we replace to `basic_derives`, there comes an additional step to figure out what `basic_derives` does.

e.g.
https://github.com/gluesql/gluesql/blob/efe46c1676fe194faffe866d396fcde04f504c37/core/src/result.rs#L77

If we can declare that kind of step in our existing code base, then it would be fine.
`gluesql::Result` would be a good example which is common pattern used by many Rust projects.
This `Result` hides `Error` type but users can easily check what `Result` means because that is also declared in the same workspace.

So...
If there exists standalone proc macro crate `basic_derives` and we can declare what traits to include in the `core` workspace, that would be awesome.
Reduce lots of redundant code, easier to maintain and less-mistake expected.

However, current `gluesql-pm` is not standalone and it only exists for gluesql workspaces.
And because it is a separate crate, users cannot figure out easily when they see `#[basic_derives]`.
To check what it does, they need to read `gluesql-pm` codes.


It would be the best if we can declare a kind of macro variable and re-use it.
Something like below...

e.g.
```rust
#basic_derives = (Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)

#[basic_derives] 
pub enum SetExpr {
    ...
}
```

If this kind approach could work, then... this proc_macro crate can be an one of essential crates which will be used by tons of Rust projects. :)

**Comment by MRGRAVITY817** [comment]
I get your point. I have also seen that `serde` and `diesel` crate also create a **subcrate within subcrate** for providing proc-macros for specific workspace. So I should definitely rename the `gluesql-pm` to `basic-derive-macro` and move in to `gluesql-core`.

About the problem that user might get confused for realizing the role of `#[basic_derives]`, I think giving a documented comment `/// explanation` will be sufficient not to confuse them. Since lot's of modern IDEs(+ vim with some plugins) displays definition window when hovering over the code or has go-to-definition functions with shortcuts, so I don't think this would matter much. 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/41038636/168823446-32deb690-8381-46c4-b26e-f008dbd24459.png">
