### ISSUE TITLE
support Rand() function

### ISSUE THREAD

**Issue by ghost** [gluesql/gluesql#593]
support the rand() function (random).  optional parameter seed.
see
[https://www.w3schools.com/sql/func_mysql_rand.asp](https://www.w3schools.com/sql/func_mysql_rand.asp)

**Comment by earney** [comment]
I can look into implementing this.

**Comment by earney** [comment]
One issue I see with this.  And it is probably because of my lack of understanding Rust.
We will need to create a global variable to hold the random instance so that after we get the seed, we can call the random instance and get the same list of numbers for each run.  What do you guys recommend we do?  Can someone suggest how/where to create the random instance variable so it can be used when RAND() or RAND(seed) is called?

**Comment by earney** [comment]
PR #595 implements this request.
