### ISSUE TITLE
[Discussion] Set `rust-toolchain` file to `stable` 

### ISSUE THREAD

**Issue by MRGRAVITY817** [gluesql/gluesql#628]
## Should be set as `stable`, rather than version number
By far we've been making PR for every rust-lang stable release, setting the latest version number.  
However this can be cumbersome since the release cycle kinda short.  

How about just setting it as `stable`?  
Ref: https://github.com/sqlparser-rs/sqlparser-rs/blob/main/rust-toolchain

I'd like to know if this is a good or bad idea.

**Comment by panarch** [comment]
I think the current way that specifying the version number explicitly would fit better for our use cases.
This is mainly because of preventing unexpected Github Action failure on rust clippy.

We are currently applying quite strict rule of clippy which returns error even for warnings.

If we don't specify the exact version number, stable version update can be made during the pull request is open & in review. (it happens automatically by GitHub Action)
Then, the PR author may needs to do unnecessary task (applying clippy rule updates) which is not related to the PR itself.

**Comment by ever0de** [comment]
> I think the current way that specifying the version number explicitly would fit better for our use cases. This is mainly because of preventing unexpected Github Action failure on rust clippy.
> 
> We are currently applying quite strict rule of clippy which returns error even for warnings.
> 
> If we don't specify the exact version number, stable version update can be made during the pull request is open & in review. (it happens automatically by GitHub Action) Then, the PR author may needs to do unnecessary task (applying clippy rule updates) which is not related to the PR itself.

I agree with this.
It would be nice to clarify which version we are implementing.

**Comment by MRGRAVITY817** [comment]
Thanks for great opinions. That makes sense.
