### ISSUE TITLE
Testdata from file and/or stdin

### ISSUE THREAD

**Issue by willy610** [gluesql/gluesql#73]
Love this project.
Have a lot of sql database dumps I want to have for verification
A separate bin project can't refer to locally libraries.

But a rough approach is to introduce tests for loading sql from a file instead of inline strings

Give me a hint where to start in my downloaded glusql-main

**Comment by panarch** [comment]
Thanks!

> But a rough approach is to introduce tests for loading sql from a file instead of inline strings
This sounds really good, I agree that running tests from files can be certainly useful when we consider to run other database's sql test cases for verification.

For the beginning, it would be good to see [examples/api_usage.rs](https://github.com/gluesql/gluesql/blob/main/examples/api_usage.rs)

It would be good to add a new example code which loads sql file and runs.

**Comment by willy610** [comment]
I work like an anarchist for a moment. Off group.
Align later on in some way, if it suites you

(The published gluesql = { version = "0.1.15", features = ["sled-storage"] } is not the same as what's committed on the project,
alright? So there is no multi line insert and others I need when importing more volumes)

So I stick to the downloaded source and will try to add test case for file load.

By the way I have already modified so that 'SingleQuotedString' is accepted in sql-statements. 
More SQL-standard.
(Verified at insert sofar).
Today only DoubleQuotedString is accepted.

**Comment by panarch** [comment]
That sounds good,
Yes that's true, after "0.1.15" released, there were lots of improvements newly made, thanks to @ryanhossain9797 and @leoppro 
New version release is required but I didn't do that yet.

I was planning to release "0.1.16" after I add `GROUP BY` supports and I estimated `GROUP BY` issue as a single week one.
But.... it took quite a long more, so that's the reason of this delay.
I'll release new version next week, then you will be able to use using version numbers.

Also thanks a lot for reporting bug, yeah at the beginning I wasn't aware about that 'SingleQuotedString' is not SQL-standard.
If you are ok, can you please add this 'SingleQuotedString' issue to issue stack with problematic SQL samples?

**Comment by willy610** [comment]
It's a pitty column expression and table expression can't be named and referenced

#80, #82

**Comment by panarch** [comment]
@willy610 That issues don't mean that table expressions can't be named and referenced, it is still possible.

* #82 is an independent issue.
* #80 is a prior issue for providing name & reference functions.

**Comment by panarch** [comment]
This is too far to think at this time.
Let's make it again when we can consider more details.
